-- ---------------------------------------------------------------------------
-- 002_seed_default_list.sql  (generated by scripts/generate-default-list-sql.mjs)
--
-- Seeds the SF Chronicle Top 100 as a real lists row owned by kidhack so
-- the rest of the app can treat it like any other custom list. Idempotent:
-- safe to re-run after editing data/restaurants.js (regenerate this file
-- by running the script).
--
-- Prerequisite: kidhack@kidhack.com must have signed in at least once so the
-- corresponding auth.users row exists. The DO block raises if it doesn't.
-- ---------------------------------------------------------------------------

do $$
declare
  owner       uuid;
  new_list_id uuid;
begin
  select id into owner from auth.users where email = 'kidhack@kidhack.com';
  if owner is null then
    raise exception
      'kidhack@kidhack.com has not signed in yet -- have them sign in, then rerun this migration';
  end if;

  insert into public.profiles (user_id, username)
  values (owner, 'kidhack')
  on conflict (user_id) do nothing;

  insert into public.lists (owner_id, slug, name)
  values (owner, 'chronicle-top-100-2026', 'SF Chronicle Top 100 - 2026')
  on conflict (slug) do update set
    name       = excluded.name,
    updated_at = now()
  returning id into new_list_id;

  insert into public.list_items (list_id, rank, name, address, city, cuisine, url, lat, lng) values
      (new_list_id, 1, 'Four Kings', '710 Commercial St.', 'San Francisco', 'Cantonese', 'https://www.itsfourkings.com/', 37.794093, -122.405068),
      (new_list_id, 2, 'The Progress', '1525 Fillmore St.', 'San Francisco', 'Californian', 'https://theprogress-sf.com/', 37.783661, -122.433076),
      (new_list_id, 3, 'Burdell', '4640 Telegraph Ave.', 'Oakland', 'Soul food', 'https://www.burdelloakland.com/', 37.833928, -122.26312),
      (new_list_id, 4, 'Copra', '1700 Fillmore St.', 'San Francisco', 'South Indian', 'https://www.coprarestaurant.com/', 37.78536, -122.432842),
      (new_list_id, 5, 'Sun Moon Studio', '1940 Union St., Suite 21', 'Oakland', 'Fine dining', 'https://www.sunmoonstudio.com', 37.8144902, -122.2860402),
      (new_list_id, 6, 'Popoca', '906 Washington St.', 'Oakland', 'Salvadoran', 'https://www.popocaoakland.com', 37.801346, -122.274453),
      (new_list_id, 7, 'Breadbelly', '1408 Clement St.', 'San Francisco', 'Asian American bakery', 'https://www.breadbellysf.com/', 37.782751, -122.474399),
      (new_list_id, 8, 'Rich Table', '199 Gough St.', 'San Francisco', 'American', 'https://www.richtablesf.com/', 37.77485, -122.422843),
      (new_list_id, 9, 'SingleThread', '131 North St.', 'Healdsburg', 'Fine dining', 'https://singlethreadfarms.com/', 38.612435, -122.869694),
      (new_list_id, 10, 'Fù Huì Huá', '2809 24th St.', 'San Francisco', 'Fine dining', 'https://www.fuhuihua.com/', 37.7527, -122.408433),
      (new_list_id, 11, 'Taishan Cuisine', '781 Broadway', 'San Francisco', 'Cantonese', 'https://www.taishancuisine2288.com/', 37.797268, -122.409846),
      (new_list_id, 12, 'Jules', '237 Fillmore St.', 'San Francisco', 'Pizza', 'https://www.julespizza.co/', 37.77177, -122.4306),
      (new_list_id, 13, 'Soba Ichi', '2311A Magnolia St.', 'Oakland', 'Japanese', 'https://sobaichioakland.com/', 37.817068, -122.285025),
      (new_list_id, 14, 'Joodooboo', '4201 Market St.', 'Oakland', 'Korean', 'https://joodooboo.co/', 37.83255, -122.273742),
      (new_list_id, 15, 'True Laurel', '753 Alabama St.', 'San Francisco', 'American', 'https://truelaurelsf.com/', 37.759501, -122.411459),
      (new_list_id, 16, 'Friends Only', '1501 California St.', 'San Francisco', 'Sushi', 'https://www.instagram.com/friendsonlysf/', 37.790592, -122.419252),
      (new_list_id, 17, 'Benu', '22 Hawthorne St.', 'San Francisco', 'Fine dining', 'https://www.benusf.com/', 37.785436, -122.399214),
      (new_list_id, 18, 'Quince', '470 Pacific Ave.', 'San Francisco', 'Fine dining', 'https://www.quincerestaurant.com/', 37.797502, -122.403368),
      (new_list_id, 19, 'Tacos Oscar', '420 40th St.', 'Oakland', 'Mexican', 'https://www.tacososcar.com/', 37.828799, -122.260409),
      (new_list_id, 20, 'San Ho Won', '2170 Bryant St.', 'San Francisco', 'Korean', 'https://www.sanhowon.com', 37.759442, -122.410179),
      (new_list_id, 21, 'Sons & Daughters', '2875 18th St', 'San Francisco', 'Fine dining', 'https://www.sonsanddaughterssf.com', 37.761625, -122.410849),
      (new_list_id, 22, 'Mägo', '3762 Piedmont Ave.', 'Oakland', 'Fine dining', 'https://www.magorestaurant.com', 37.823599, -122.256041),
      (new_list_id, 23, 'Sandy’s', '1457 Haight St.', 'San Francisco', 'NOLA sandwiches', 'https://www.sandysmuffs.com', 37.769802, -122.44629),
      (new_list_id, 24, 'Bombera', '3459 Champion St.', 'Oakland', 'Mexican', 'https://www.bomberaoakland.com', 37.799536, -122.215098),
      (new_list_id, 25, 'Verjus', '528 Washington St.', 'San Francisco', 'French wine bar', 'https://www.verjuscave.com', 37.795826, -122.402521),
      (new_list_id, 26, 'Californios', '355 11th St.', 'San Francisco', 'Fine dining', 'https://www.californiossf.com', 37.771467, -122.412872),
      (new_list_id, 27, 'Rose Pizzeria', '1960 University Ave.', 'Berkeley', 'Pizza', 'https://www.rosepizzeria.com', 37.871415, -122.271384),
      (new_list_id, 28, 'Delfina', '3621 18th St.', 'San Francisco', 'Italian', 'https://www.delfinasf.com', 37.761362, -122.424189),
      (new_list_id, 29, 'Atelier Crenn', '3127 Fillmore St.', 'San Francisco', 'Fine dining', 'https://www.ateliercrenn.com', 37.798371, -122.436045),
      (new_list_id, 30, 'Ok’s Deli', '3932 Telegraph Ave.', 'Oakland', 'Asian American deli', 'https://oksdeli.com', 37.82863, -122.264547),
      (new_list_id, 31, 'Minnie Bell’s Soul Movement', '1375 Fillmore St.', 'San Francisco', 'Soul food', 'https://www.minniebellssoul.com', 37.782071, -122.432708),
      (new_list_id, 32, 'Hilda and Jesse', '701 Union St.', 'San Francisco', 'Fine dining', 'https://www.hildaandjessesf.com', 37.800052, -122.411033),
      (new_list_id, 33, 'Zuni Café', '1658 Market St.', 'San Francisco', 'Californian', 'http://zunicafe.com', 37.7736, -122.421608),
      (new_list_id, 34, 'Madcap', '198 Sir Francis Drake Blvd.', 'San Anselmo', 'Fine dining', 'https://www.madcapmarin.com', 37.974754, -122.561473),
      (new_list_id, 35, 'Lunette', '1 Ferry Building, Suite 33/47', 'San Francisco', 'Cambodian', 'https://www.lunettecambodia.com', 37.796787, -122.393299),
      (new_list_id, 36, 'State Bird Provisions', '1529 Fillmore St.', 'San Francisco', 'Californian', 'https://www.statebirdsf.com', 37.783661, -122.433076),
      (new_list_id, 37, 'Flour + Water', '2401 Harrison St.', 'San Francisco', 'Italian', 'https://www.flourandwater.com', 37.758923, -122.412185),
      (new_list_id, 38, 'La Vaca Birria', '2962 24th St.', 'San Francisco', 'Mexican', 'https://www.lavacabirria.com', 37.75289, -122.411391),
      (new_list_id, 39, 'Aziza', '5800 Geary Blvd.', 'San Francisco', 'Moroccan', 'https://www.azizasf.com', 37.780541, -122.481714),
      (new_list_id, 40, 'Bo Ne Phu Yen', '1818 Tully Road', 'San Jose', 'Vietnamese', 'https://www.instagram.com/bonephuyen/', 37.321996, -121.823061),
      (new_list_id, 41, 'Fikscue', '1708 Park St.', 'Alameda', 'Indonesian-Texas barbecue', 'https://www.fikscue.com/', 37.768274, -122.238897),
      (new_list_id, 42, 'Lily', '225 Clement St.', 'San Francisco', 'Vietnamese', 'https://www.lilyonclement.com/', 37.7828365, -122.4616947),
      (new_list_id, 43, 'LeYou Ethiopian', '1100 N. First St., Suite C', 'San Jose', 'Ethiopian', 'https://leyouethiopian.com/', 37.356601, -121.905332),
      (new_list_id, 44, 'Mijoté', '2400 Harrison St.', 'San Francisco', 'French', 'https://www.mijotesf.com/', 37.758894, -122.412746),
      (new_list_id, 45, 'Nari', '1625 Post St.', 'San Francisco', 'Thai', 'https://www.narisf.com/', 37.785561, -122.428705),
      (new_list_id, 46, 'Tanzie’s', '1453 Dwight Way', 'Berkeley', 'Thai', 'https://www.tanziescafe.com/', 37.8621875, -122.281927),
      (new_list_id, 47, 'Mister Jiu’s', '28 Waverly Place', 'San Francisco', 'Chinese', 'https://www.misterjius.com/', 37.793519, -122.406524),
      (new_list_id, 48, 'Yeobo, Darling', '827 Santa Cruz Ave.', 'Menlo Park', 'Korean Taiwanese', 'https://www.yeobodarling.com/', 37.450467, -122.185181),
      (new_list_id, 49, 'Dalida', '101 Montgomery St., Suite 100', 'San Francisco', 'Mediterranean', 'https://www.dalidasf.com/', 37.800033, -122.459579),
      (new_list_id, 50, 'La Taqueria', '2889 Mission St', 'San Francisco', 'Mexican', 'https://lataqueriasf.net/', 37.750874, -122.418158),
      (new_list_id, 51, 'Cotogna', '490 Pacific Ave', 'San Francisco', 'Italian', 'https://www.cotognasf.com/', 37.7974582, -122.4034024),
      (new_list_id, 52, '3 Bottled Fish', '1924 35th Ave', 'Oakland', 'Vietnamese', 'https://3bottledfish.square.site/', 37.7828651, -122.2186265),
      (new_list_id, 53, 'Prubechu', '2224 Mission St., A', 'San Francisco', 'Chamorro', 'https://www.prubechu.com/', 37.761319, -122.419733),
      (new_list_id, 54, 'Valley', '487 1st St W', 'Sonoma', 'Wine bar', 'https://www.valleybarandbottle.com/', 38.2923068, -122.4591207),
      (new_list_id, 55, 'Kitchen Istanbul', '349 Clement St.', 'San Francisco', 'Turkish', 'https://www.kitchenistanbulsf.com/', 37.78276, -122.463114),
      (new_list_id, 56, 'Side A', '2814 19th St.', 'San Francisco', 'American', 'https://www.sideasf.com/', 37.760616, -122.410546),
      (new_list_id, 57, 'Liholiho Yacht Club', '871 Sutter St.', 'San Francisco', 'American', 'https://lycsf.com/', 37.788178, -122.414583),
      (new_list_id, 58, 'Kin Khao', '55 Cyril Magnin St.', 'San Francisco', 'Thai', 'https://www.kinkhao.com/', 37.784878, -122.408965),
      (new_list_id, 59, 'Cultured Pickle Shop', '800 Bancroft Way', 'Berkeley', 'Californian', 'https://www.culturedpickleshop.com/', 37.86311, -122.296843),
      (new_list_id, 60, 'Lou’s Takeaway', '621A Del Ganado Road', 'San Rafael', 'Californian', 'https://www.loustakeaway.com/', 38.013455, -122.559454),
      (new_list_id, 61, 'The Happy Crane', '451 Gough St', 'San Francisco', 'Cantonese', 'https://www.thehappycranesf.com/', 37.777491, -122.4233),
      (new_list_id, 62, 'Vik’s Chaat', '2390 Fourth St.', 'Berkeley', 'Indian', 'https://vikschaat.com/', 37.861381, -122.298419),
      (new_list_id, 63, 'Peña’s Bakery', '3355 Foothill Blvd.', 'Oakland', 'Mexican deli', 'https://www.instagram.com/penabakery/', 37.782997, -122.220984),
      (new_list_id, 64, 'Azalina’s', '499 Ellis St.', 'San Francisco', 'Malaysian', 'https://www.azalinas.com/', 37.784584, -122.414148),
      (new_list_id, 65, 'Spicy Joi', '1687 Willow Pass Rd.', 'Concord', 'Laotian', 'https://www.spicyjoibanhmi.com/', 37.973734, -122.042368),
      (new_list_id, 66, 'Via Aurelia', '300 Toni Stone Xing, Suite A', 'San Francisco', 'Italian', 'https://www.viaaureliasf.com/', 37.775773, -122.388653),
      (new_list_id, 67, 'Kunjip', '1066 Kiely Blvd.', 'Santa Clara', 'Korean', 'https://kunjip.shop/', 37.345975, -121.978216),
      (new_list_id, 68, 'Cyrus', '275 CA-128', 'Geyserville', 'Fine dining', 'https://www.cyrusrestaurant.com/', 38.706405, -122.900453),
      (new_list_id, 69, 'Psychic Pie', '980 Gravenstein Hwy. S.', 'Sebastopol', 'Pizza', 'https://psychicpie.com/', 38.390783, -122.816695),
      (new_list_id, 70, 'Eylan', '500 El Camino Real', 'Menlo Park', 'Indian', 'https://www.eylanrestaurant.com/', 37.451145, -122.177326),
      (new_list_id, 71, 'Wolfsbane', '2495 3rd St.', 'San Francisco', 'Fine dining', 'https://wolfsbanesf.com/', 37.758065, -122.388152),
      (new_list_id, 72, 'Itria', '3266 24th St.', 'San Francisco', 'Italian', 'https://www.itriasf.com/', 37.752494, -122.41781),
      (new_list_id, 73, 'Sirene', '3308 Grand Ave.', 'Oakland', 'American', 'https://sirene-oak.com/', 37.812832, -122.246755),
      (new_list_id, 74, 'Rintaro', '82 14th St.', 'San Francisco', 'Japanese', 'https://izakayarintaro.com/', 37.768814, -122.415111),
      (new_list_id, 75, 'Table Culture Provisions', '312 Petaluma Blvd. S.', 'Petaluma', 'Fine dining', 'https://www.tcprovision.com/', 38.231637, -122.635065),
      (new_list_id, 76, 'Spread Kitchen', '18375 Highway 12', 'Sonoma', 'Lebanese', 'https://www.spreadkitchensonoma.com/', 38.311578, -122.479894),
      (new_list_id, 77, 'Mustards Grill', '7399 St. Helena Hwy.', 'Napa', 'American', 'https://www.mustardsgrill.com/', 38.418969, -122.388169),
      (new_list_id, 78, 'Scoma’s', '1965 Al Scoma Way', 'San Francisco', 'Seafood', 'https://scomas.com/', 37.8089477, -122.4184344),
      (new_list_id, 79, 'Jubba', '5330 Terner Way', 'San Jose', 'Somali', 'https://jubbarestaurant.site', 37.257424, -121.861023),
      (new_list_id, 80, 'Smish Smash', '945 Market St.', 'San Francisco', 'Burgers', 'https://www.smish-smash.com/', 37.783048, -122.408632),
      (new_list_id, 81, 'Reem’s', '2901 Mission St.', 'San Francisco', 'Middle Eastern', 'https://www.reemscalifornia.com/', 37.750531, -122.418077),
      (new_list_id, 82, 'Cafe Colucci', '5849 San Pablo Ave.', 'Oakland', 'Ethiopian', 'https://cafecolucci.com/', 37.841857, -122.283714),
      (new_list_id, 83, 'Saison', '178 Townsend St.', 'San Francisco', 'Fine dining', 'https://saisonsf.com/', 37.779734, -122.392524),
      (new_list_id, 84, 'Enclos', '139 E Napa St.', 'Sonoma', 'Fine dining', 'https://enclos-sonoma.com/', 38.291519, -122.455846),
      (new_list_id, 85, 'The Laundromat', '3725 Balboa St.', 'San Francisco', 'Pizza', 'https://www.thelaundromatsf.com/', 37.775396, -122.498867),
      (new_list_id, 86, 'The Charter Oak', '1050 Charter Oak Ave.', 'St. Helena', 'American', 'https://www.thecharteroak.com/', 38.501786, -122.464102),
      (new_list_id, 87, 'Goodtime Bar', '30 Fountain Alley #160', 'San Jose', 'Californian', 'https://www.goodtimebarsj.com/', 37.336204, -121.889545),
      (new_list_id, 88, 'House of Prime Rib', '1906 Van Ness Ave.', 'San Francisco', 'Steakhouse', 'https://www.houseofprimerib.net/', 37.793381, -122.422502),
      (new_list_id, 89, 'Ernest', '1890 Bryant St., Suite 100', 'San Francisco', 'Californian', 'https://www.ernestsf.com/', 37.763237, -122.410712),
      (new_list_id, 90, 'Alem’s Coffee', '5353 Claremont Ave.', 'Oakland', 'Eritrean', 'https://alemscoffee.wixsite.com/site', 37.840328, -122.259833),
      (new_list_id, 91, 'Ippuku', '2130 Center St., Suite 101', 'Berkeley', 'Japanese', 'https://ippukuberkeley.com/', 37.870162, -122.267054),
      (new_list_id, 92, 'Keeku da Dhaba', '39935 Mission Blvd.', 'Fremont', 'Indian', 'https://www.keekuz.com/', 37.556832, -121.952386),
      (new_list_id, 93, 'El Molino Central', '11 Central Ave.', 'Sonoma', 'Mexican', 'https://www.elmolinocentral.com', 38.315122, -122.482002),
      (new_list_id, 94, 'Mrs Khan Uyghur Cuisine', '712 Santa Cruz Ave.', 'Menlo Park', 'Uyghur', 'https://www.mrskhanuyghur.com/', 37.452093, -122.184677),
      (new_list_id, 95, 'Mashaallah Halal Pakistani Food', '315 5th St.', 'San Francisco', 'Pakistani', 'https://mashallahhalalfood.com/', 37.780098, -122.402901),
      (new_list_id, 96, 'Patio Filipino', '1770 El Camino Real', 'San Bruno', 'Filipino', 'https://www.patiofilipino.com', 37.614872, -122.405512),
      (new_list_id, 97, 'Capital', '839 Clay St.', 'San Francisco', 'Cantonese', 'https://www.sfchronicle.com/projects/2026/top-100-best-restaurants-san-francisco-bay-area/#capital-listing', 37.794012, -122.407078),
      (new_list_id, 98, 'Yo También Cantina', '205 Hugo St.', 'San Francisco', 'Café', 'https://www.ytc2go.com/', 37.765114, -122.460229),
      (new_list_id, 99, 'Shizen', '370 14th St.', 'San Francisco', 'Vegan Sushi', 'https://www.shizensf.com/', 37.768328, -122.421641),
      (new_list_id, 100, 'Lazy Bear', '3416 19th St.', 'San Francisco', 'Fine dining', 'https://www.lazybearsf.com/', 37.760395, -122.419712)
  on conflict (list_id, rank) do update set
    name    = excluded.name,
    address = excluded.address,
    city    = excluded.city,
    cuisine = excluded.cuisine,
    url     = excluded.url,
    lat     = excluded.lat,
    lng     = excluded.lng;
end $$;
